#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Job
apiVersion: batch/v1
metadata:
  name: orb-add-followers
spec:
  template:
    spec:
      volumes:
        - name: ca-cert
          configMap:
            name: orb-add-followers-ca-cert
      containers:
      - name: orb-add-followers
        volumeMounts:
          - name: ca-cert
            mountPath: /etc/orb-add-followers/tls
