#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: did-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did-resolver
  template:
    metadata:
      labels:
        app: did-resolver
    spec:
      volumes:
        - name: config
          configMap:
            name: did-resolver-config
      containers:
      - name: did-resolver
        envFrom:
          - configMapRef:
              name: did-resolver-env
        image: did-resolver:latest
        args: ["start"]
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
        volumeMounts:
          - name: config
            mountPath: /etc/did-resolver/config
            readOnly: true
